### ISSUE TITLE
add an API endpoint to get smaller web-compatible images

### ISSUE THREAD

**Issue by MoralCode** [AdenFlorian/random.dog#6]
As I said in my other issue (#5), I am currently integrating your API into a web app and I would like to suggest this as a feature so that my web app doesn't impact your hosting costs too much.

maybe you could add an API endpoint or something to automatically get a scaled-down version of the image (maybe a URL like `https://random.dog/woof?width=200&height=200` to scale all images to 200x200px or something?

just an idea
-DeveloperACE

**Comment by adenflorian** [comment]
Yea, it's on my list to scale down images that are waaay too big. Once I do that then I'll look into this issue, thanks!

**Comment by MoralCode** [comment]
to me it seems more like an image resolution thing and not necessarily a size/scale thing. ¯\_(ツ)_/¯

**Comment by adenflorian** [comment]
Sorry, I meant downsizing the pictures that are on the server, and downsizing them on upload.

**Comment by MoralCode** [comment]
idk really what I was thinking with this anyway so ¯\_(ツ)_/¯

**Comment by adenflorian** [comment]
@DeveloperACE I'm working on it right now, and using [jimp](https://github.com/oliver-moran/jimp) it's pretty slow. Can take up to 2 seconds to read and resize.

**Comment by adenflorian** [comment]
@DeveloperACE Since the solution I was looking at looks like it will affect performance a bit, I'd rather not implement any kind of server side resizing at the moment. The hosting plan I have is flat rate per month with no bandwidth limit, so don't worry about impacting any costs for me 😄. Thanks for your concern though.

I will still probably work on a way to downsize images on upload and downsize existing images so users have a more consistent experience.

**Comment by MoralCode** [comment]
@AdenFlorian who do you use as a host?

**Comment by adenflorian** [comment]
@DeveloperACE digitalocean.com

**Comment by MoralCode** [comment]
https://github.com/AdenFlorian/random.dog/issues/7
https://github.com/AdenFlorian/random.dog/issues/8

just figured I'd link these here in case anyone else happens by this page (hope you don't mind)
